### PR TITLE
Resolve #1 Less Verbose

### LINKED ISSUE #1: less verbose (docs missing)
When starting the router, set an option,flat to avoid printing the added routes.

### PR DESCRIPTION
**Pull request by Harnish**

### CODE REVIEW

**Comment by Harnish** [comment]
Resolve #1 

Not sure what the checks are trying to do but I didn't change the items it is dying on.

**Comment by Harnish** [comment]
Research into the issues, it looks like a docker misconfiguration, trying to import a base go library.

**Comment by nbari** [comment]
Thanks @Harnish could you please push to branch develop not master

**Comment by Harnish** [comment]
will do

**Comment by Harnish** [comment]
Can I hold it until Oct1 ?

**Comment by nbari** [comment]
sure no problem, meanwhile could be nice to add the unit test to cover 100%

**Pull request closed without merging**
